name: "mydemo"


on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        run: |
          source ${GITHUB_ACTION_PATH}/echo.sh
        shell: bash
