name: "mydemo"


on:
  push:
    branches: [ "main" ]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "GITHUB_WORKFLOW = $GITHUB_WORKFLOW"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME"
          echo "GITHUB_JOB = $GITHUB_JOB"
          echo "GITHUB_REF = $GITHUB_REF"
          echo "GITHUB_ACTION_PATH = $GITHUB_ACTION_PATH"
          echo "github.action_path = ${{ github.action_path }}"
          source ${GITHUB_WORKSPACE}/echo.sh
        shell: bash
